### ISSUE TITLE
context_services replaces contexts: not able to use mink context and own contexts

### ISSUE THREAD

**Issue by jcornide** [FriendsOfBehat/ContextServiceExtension#7]
Hi,

I started to using your extension and I think its's a great idea, so I defined my behat.yml as this:
```

default:
    suites:
        default:
            contexts_services:
                - acme.context.user
            contexts:
                - Behat\MinkExtension\Context\MinkContext
```

But seems like I can not use both contexts_services and contexts. When I do this I miss the MinkContext steps.

Am I doing something wrong or is the way is supposed to work? Is there a workaround for this?

Thanks!

**Comment by pamil** [comment]
Thanks for reporting! The environments handling in Behat allows only for one of either `contexts` or `contexts_services` to be used at once, so it's not currently possible to use both of them in the same suite. 

I'm sure it can be hacked some way, but I won't find time for it in the nearest future. The quick-fix solution is to use `FriendsOfBehat\CrossContainerExtension` with the following services defined:

```xml
<service id="mink.default_session" class="Behat\Mink\Session" lazy="true" public="false">
    <factory service="__behat__.mink" method="getSession" />
</service>

<service id="mink.context" class="Behat\MinkExtension\Context\MinkContext">
    <argument type="service" id="mink.default_session" />
    <tag name="fob.context_service" />
</service>
```

Then you can use `mink.context` context service instead.

**Comment by arnolanglade** [comment]
I have already tried that 
```yaml
    mink.context:
        class: 'Behat\MinkExtension\Context\MinkContext'
        calls:
            - [setMink, ['@__behat__.mink']]
        tags:
            - { name: fob.context_service }
```
but I got
```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]               
  The service "mink.context" has a dependency on a non-existent service "__behat__.mink". 
```
My behat.yml
```
default:
    extensions:
        FriendsOfBehat\CrossContainerExtension: ~
        FriendsOfBehat\SymfonyExtension: ~
        FriendsOfBehat\ContextServiceExtension:
            imports:
               - "features/bootstrap/config/context.yml"
        Behat\MinkExtension:
            base_url: 'http://127.0.0.1:8000'
            sessions:
                default:
                    goutte: ~
    suites:
        employee:
            contexts_services:
                - al.context.employee
                - al.context.database
```
