### ISSUE TITLE
Not able to use Behat extensions with context.initializer tag

### ISSUE THREAD

**Issue by alOneh** [FriendsOfBehat/ContextServiceExtension#8]
Hi,

I use an extension which use the `context.initializer` tag of Behat but it doesn't initialize when I use context as services. My config looks like :

```
default:
    extensions:
        Codifico\ParameterBagExtension\ServiceContainer\ParameterBagExtension:
            parameter_bag:
                class: Codifico\ParameterBagExtension\Bag\InMemoryPlaceholderBagBut
```

Is there a workaround to get this kind of extension working again ?

Thanks!
